### ISSUE TITLE
Not compatable with current version of VS Code 1.71.2

### ISSUE THREAD

**Issue by jhs88** [ai-genie/chatgpt-vscode#1]
### Verify it's not a duplicate bug report

- [X] I searched for similar bugs reported on GitHub and nobody has reported a similar issue. <a href="https://github.com/ai-genie/vscode-chatgpt/issues?q=" target="_blank">Search all issuees</a>.
- [X] I read <a href="https://github.com/ai-genie/vscode-chatgpt#troubleshooting" target="_blank">Troubleshooting guide on Readme</a> and there is not a guide on how to solve my problem.

### Describe the Bug

I cannot download this plugin on the latest version of VSCode. What is the correct version I should be using? I'm currently using Windows. The plugin works fine on my Mac

### Please tell us if you have customized any of the extension settings or whether you are using the defaults.

N/A

**Comment by genieai-info** [comment]
Hello - The minimum version of VS Code the extension requires is 1.73. Please update your VS Code on your Windows machine. The latest VS Code on Windows is `Version: 1.76.2`
