### ISSUE TITLE
Always raise 404 error when using gpt-4 model and in conversation view. It works with editor view. And my account did subscribe to gpt-plus and have access to GPT-4.

### ISSUE THREAD

**Issue by GreyWuLB** [ai-genie/chatgpt-vscode#10]
### Verify it's not a duplicate bug report

- [X] I searched for similar bugs reported on GitHub and nobody has reported a similar issue. <a href="https://github.com/ai-genie/vscode-chatgpt/issues?q=" target="_blank">Search all issuees</a>.
- [X] I read <a href="https://github.com/ai-genie/vscode-chatgpt#troubleshooting" target="_blank">Troubleshooting guide on Readme</a> and there is not a guide on how to solve my problem.

### Describe the Bug

Always raise 404 error when using gpt-4 model and in conversation view. It works with editor view. And my account did subscribe to gpt-plus and have access to GPT-4.
<img width="444" alt="image" src="https://user-images.githubusercontent.com/102022925/226812411-ecba9853-bfc3-4da8-8d87-b1de8a5ba8b0.png">

### Please tell us if you have customized any of the extension settings or whether you are using the defaults.

  "genieai.openai.temperature": 0,
  "genieai.personalizedName": "MyName",
  "genieai.openai.model": "gpt-4"

**Comment by genieai-info** [comment]
Hi - Please check this: https://github.com/ai-genie/chatgpt-vscode/issues/6. The editor view is defaulted to `text-davinci-003` model, that's why it works but you probably don't have GPT-4 API access yet (Turbo Plus subscription doesn't grant you the GPT-4 API access - only web)
