### ISSUE TITLE
如何删除Issues问题？

### ISSUE THREAD

**Issue by WoHaoKun21** [ai-genie/chatgpt-vscode#105]
如何删除Issues问题？
![Snipaste_2023-06-12_14-09-49](https://github.com/ai-genie/chatgpt-vscode/assets/90443926/e9ccb35c-b22d-435f-9c7c-9a0dd2b2b292)

**Comment by DreamPanda5127** [comment]
I fix it by rewriting the settings.json file in C:\Users\Your User Name\AppData\Roaming\Code\User.
I could not be sure what I did wrong.
So I removed all content in it then it is working well.

I hope this will help u.

**Comment by WoHaoKun21** [comment]
> 
现在可以用了，估计是版本更新后和WIN11不适配了

**Comment by WoHaoKun21** [comment]
> 我通过重写 C:\Users\Your User Name\AppData\Roaming\Code\User 中的 settings.json 文件来修改它。我不确定我做错了什么。所以我删除了其中的所有内容 ， 然后它运行良好。 也许您可以更改唯一需要的属性。
> 
> 我希望这会帮助你。
现在可以用了，估计是版本更新后和WIN11不适合配了

**Comment by WoHaoKun21** [comment]
> 



> 

谢谢，我去试试

**Comment by WoHaoKun21** [comment]
> 我通过重写 C:\Users\Your User Name\AppData\Roaming\Code\User 中的 settings.json 文件来修改它。我不确定我做错了什么。所以我删掉了其中的所有内容， 然后 它运行良好。 也许您可以更改唯一需要的属性。
> 
> 我希望这会帮助你。

谢谢，我去试一试

**Comment by genieai-info** [comment]
Sorry - I don't understand this language and what the question is. Please re-ask it in English if you still need help
