### ISSUE TITLE
This project is dead guys, find another one.

### ISSUE THREAD

**Issue by Cytranics** [ai-genie/chatgpt-vscode#108]
### Describe the feature

wef

**Comment by DhavalThkkar** [comment]
Do you have any suggestions?

**Comment by Cytranics** [comment]
Sadly its still better than all the others... I've reverse engineered the plugin, added support for more conversations history, added support for changing the system prompt. cory@cytranic.com email me I can send you my version and the code, its obscured but if you have a little knowledge you should be able to make changes.

**Comment by Cytranics** [comment]
> Do you have any suggestions?

I do now, a month later. 100% refactored extention with autonomous coding:
https://marketplace.visualstudio.com/items?itemName=Autonimate.autonimate&ssr=false#review-details

**Comment by gencay** [comment]
The project is not dead, it is just not getting updates recently. Please read more about the Genie as well as the continuation of my open-source project ChatGPT Reborn by Christopher here: https://github.com/christopher-hayes/vscode-chatgpt-reborn. That project got more updates than Genie recently, but we will catch up at some point.
