### ISSUE TITLE
Model Select Update

### ISSUE THREAD

**Issue by YueyuHoshizora** [ai-genie/chatgpt-vscode#110]
### Describe the feature

The OpenAI on 06/13 update some model,
can u add in this ?

![image](https://github.com/ai-genie/chatgpt-vscode/assets/92282870/53107c44-bfd8-44ad-aa53-2cfc2b51747b)

**Comment by PierrunoYT** [comment]
Waiting too

**Comment by rafzei** [comment]
On June 27th the stable gpt-3.5-turbo will be automatically upgraded to gpt-3.5-turbo-0613, but yes - would be nice to use it right now with Genie

**Comment by nakata5577** [comment]
To add the model, the following two files must be modified.

C:\Users\<user>\.vscode\extensions\genieai.chatgpt-vscode-0.0.8\package.json
C:\Users\<user>\.vscode\extensions\genieai.chatgpt-vscode-0.0.8\out\extension.js

The modification points of each file are as follows.
・package.json

Ex:
![image](https://github.com/ai-genie/chatgpt-vscode/assets/6749435/29b25fdf-12b2-4ce9-8c21-72339f57b04a)



・extension.js

Ex:
![image](https://github.com/ai-genie/chatgpt-vscode/assets/6749435/4e95f4c7-5eeb-4427-b193-83a5f359d0bb)

**Comment by majormer** [comment]
> To add the model, the following two files must be modified.
> 
> ```
> C:\Users\<user>\.vscode\extensions\genieai.chatgpt-vscode-0.0.8\package.json
> C:\Users\<user>\.vscode\extensions\genieai.chatgpt-vscode-0.0.8\out\extension.js
> ```
> 
> The modification points of each file are as follows. ・package.json
> 
> e.g.: ![image](https://user-images.githubusercontent.com/6749435/245967260-29b25fdf-12b2-4ce9-8c21-72339f57b04a.png)
> 
> ・extension.js
> 
> e.g.: ![image](https://user-images.githubusercontent.com/6749435/245967371-4e95f4c7-5eeb-4427-b193-83a5f359d0bb.png)

This 100% patched things up until an official release is completed. Thank you so much!

**Comment by nakata5577** [comment]
@jamespacileo 

No. None in particular.

Check the settings again.

<img width="775" alt="image" src="https://github.com/ai-genie/chatgpt-vscode/assets/6749435/fcf9efe1-1859-47ab-ba66-e61883a207fd">

**Comment by nakata5577** [comment]
@jamespacileo 
I see! So the files to be modified are different in the remote development environment? That was a blind spot.
Thanks for sharing the information:-)

**Comment by thorizer** [comment]
> On June 27th the stable gpt-3.5-turbo will be automatically upgraded to gpt-3.5-turbo-0613, but yes - would be nice to use it right now with Genie

it didn't automatically change . why? still 4k limit

**Comment by Cytranics** [comment]
Guys I released my version, almost on par with genie. Full support for GPT3.5 and 4 models.
https://marketplace.visualstudio.com/items?itemName=Autonimate.autonimate&ssr=false#qna

**Comment by gencay** [comment]
Congrats @Cytranics! But all you need is Genie or a selfhosted version from my original project: https://github.com/gencay/vscode-chatgpt. Genie will receive updates soon!

In the meantime I recommend the experienced developers to just selfhost their own version from my open-source project: https://github.com/gencay/vscode-chatgpt. It's completely free and you don't need to download any 3rd party extension. You just need to update the model enums in the code and follow the instructions in the repo to install locally.

Thanks for all the interest in Genie! We will be in touch once the models are more up-to-date with OpenAI's recent models.

**Comment by Cytranics** [comment]
No congrats needed @gencay. I really wanted to use the 16k models, took it upon myself to fork your code. I'm not looking for fame or support. I loved ChatGPT, and Genie but they are falling behind. I'm more than willing to contribute to Genie but its closed. Not looking for anything. You're name is splattered all throughout Autonimate, which I can change over to Genie. Point being was, alot of people, including myself were hacking minified extention.js just to get the 16k to work. 

Chris's code does not support Azure and has un-needed roadblocks for signup and API keys. Again, could care less if someone downloads mine or not, and I'm more than willing to take it down and prop up genie.

**Comment by gencay** [comment]
@Cytranics no worries! I am glad that you liked both extensions. And I am well aware that they are falling behind in terms of the new models. There are unforeseen circumstances that lead to the slowness in development of Genie over the last months. However, still Genie offers a lot more than other options imho. I understand that people are very excited about the new models, but please understand that this is an all-free extension for the community. We will continue working on exciting features and catch up with the latest updates from OpenAI.

Drop an email so we have your contact information if you would like to support Genie's development at info@genieai.net

But since the core functionality of Genie is still operational and it offers bunch of additional features than its competitors, I prefer recommending people to either be patient with us or use my open-source project to self-host (This is IMO the best route to go if you have just a little bit TS/Web dev experience)

Thanks for being patient! 🙏

**Comment by Cytranics** [comment]
> > Guys I released my version, almost on par with genie. Full support for GPT3.5 and 4 models. [marketplace.visualstudio.com/items?itemName=Autonimate.autonimate&ssr=false#qna](https://marketplace.visualstudio.com/items?itemName=Autonimate.autonimate&ssr=false#qna)
> 
> @Cytranics it lacks quick fix feature for errors 

Yup, next update, already working locally, but I don't want to take genie's issue board for my ext. Releasing open source here tomorrow on GitHub.

**Comment by Cytranics** [comment]
> > Guys I released my version, almost on par with genie. Full support for GPT3.5 and 4 models. [marketplace.visualstudio.com/items?itemName=Autonimate.autonimate&ssr=false#qna](https://marketplace.visualstudio.com/items?itemName=Autonimate.autonimate&ssr=false#qna)
> 
> @Cytranics it lacks quick fix feature for errors

Updated, and its open source now: https://github.com/Cytranics/vscode-autonimate

**Comment by genieai-info** [comment]
Hi everyone, the new update has this now. Please check v0.0.9. Install or view on [VS Code Marketplace](https://marketplace.visualstudio.com/items?itemName=genieai.chatgpt-vscode)
