### ISSUE TITLE
Is this extension truly free?

### ISSUE THREAD

**Issue by 1alexvash** [ai-genie/chatgpt-vscode#114]
### Verify it's not a duplicate bug report

- [X] I searched for similar bugs reported on GitHub and nobody has reported a similar issue. <a href="https://github.com/ai-genie/vscode-chatgpt/issues?q=" target="_blank">Search all issuees</a>.
- [X] I read <a href="https://github.com/ai-genie/vscode-chatgpt#troubleshooting" target="_blank">Troubleshooting guide on Readme</a> and there is not a guide on how to solve my problem.

### Describe the Bug

I recently installed this extension, which prompted me to enter a key from ChatGPT. However, upon doing so, I encountered the following error message:
![image](https://github.com/ai-genie/chatgpt-vscode/assets/46556479/ecd6a1fb-4f99-4abd-8ba4-7a8b38479f30)

Is this extension truly free? It would be helpful if the documentation clearly stated whether there are any associated costs. Presently, there is no mention of pricing or any related fees in the documentation.

### Please tell us if you have customized any of the extension settings or whether you are using the defaults.

I just use defaults

**Comment by 1alexvash** [comment]
Follow-up questions:


1) If I'm already using GitHub Copilot, is it worth using this extension as well?
2) What is the purpose of paying for this extension when I can simply use ChatGPT online?

**Comment by viking1304** [comment]
> 1. If I'm already using GitHub Copilot, is it worth using this extension as well?

Probably not.

> 2. What is the purpose of paying for this extension when I can simply use ChatGPT online?

**This extension is free.**

It's OpenAI that requires you to pay to use their API. API is not part of the ChatGPT subscription, so even if you have ChatGPT Plus, you must pay to use their API.

It's easier and faster to use OpenAI inside VSCode, especially if you want to use it for code completion, explanation... but you already have that with Copilot.

This is a great choice for people who only want to pay for the actual use of the API and not to pay a subscription for Copilot or ChatGPT.

**Comment by 1alexvash** [comment]
> It's easier and faster to use OpenAI inside VSCode, especially if you want to use it for code completion, explanation... but you already have that with Copilot.

Doesn't this extension offer additional features or enhancements beyond what is already available, such as the ability to create custom prompts or smarter response generation?

**Comment by gencay** [comment]
Yes it is. You should also count that this extension and my open-source project is the first of its kind bringing the chat-like OpenAI experiences into the VS Code. So, you will see better and more advanced features compared to others.

Since it's backed by OpenAI APIs you should have the permissions and enough credit from OpenAI side to completely utilize this extension. Thanks @viking1304 btw for answering earlier!
