### ISSUE TITLE
Switching Model does not work.

### ISSUE THREAD

**Issue by ixaixim** [ai-genie/chatgpt-vscode#116]
### Verify it's not a duplicate bug report

- [X] I searched for similar bugs reported on GitHub and nobody has reported a similar issue. <a href="https://github.com/ai-genie/vscode-chatgpt/issues?q=" target="_blank">Search all issuees</a>.
- [X] I read <a href="https://github.com/ai-genie/vscode-chatgpt#troubleshooting" target="_blank">Troubleshooting guide on Readme</a> and there is not a guide on how to solve my problem.

### Describe the Bug

The default model GPT3.5 turbo works without any problems, however, when switching to any GPT4 versions, the result is a disheartening: 

```
HTTP 404 Not Found. You may have exhausted your OpenAI subscription allowance or have an expired account. You can clear your API Key from VS Code's [secrets storage](https://code.visualstudio.com/api/references/vscode-api#SecretStorage) with Genie: Clear API Key command. Check your allowance and account's expiration date here: https://platform.openai.com/account/usage.

{
    "error": {
        "message": "The model: `gpt-4-32k` does not exist",
        "type": "invalid_request_error",
        "param": null,
        "code": "model_not_found"
    }
}
```
Previous models seem to work instead. 
I believe this is a bug.

PS: this is my first issue, please ask me if it is necessary to provide more information. 

### Please tell us if you have customized any of the extension settings or whether you are using the defaults.

Settings: default.

**Comment by PierrunoYT** [comment]
You can't use it if you don't have access to it with your API key.
