### ISSUE TITLE
support gpt 3 turbo 16k context

### ISSUE THREAD

**Issue by thorizer** [ai-genie/chatgpt-vscode#117]
### Describe the feature

Is the app currently designed to support the 16k context by default? If not, is it possible to add support for it

**Comment by nakata5577** [comment]
@thorizer 
#110

**Comment by Cytranics** [comment]
Here, I updated the original ext and added a few autonomous coding features. Supports everything: https://marketplace.visualstudio.com/items?itemName=Autonimate.autonimate&ssr=false#review-details

**Comment by Dunky-Z** [comment]
looking forward to this feature

**Comment by genieai-info** [comment]
The new models are now available. Install or view on [VS Code Marketplace](https://marketplace.visualstudio.com/items?itemName=genieai.chatgpt-vscode)
