### ISSUE TITLE
New Version here:

### ISSUE THREAD

**Issue by Cytranics** [ai-genie/chatgpt-vscode#121]
### Verify it's not a duplicate bug report

- [X] I searched for similar bugs reported on GitHub and nobody has reported a similar issue. <a href="https://github.com/ai-genie/vscode-chatgpt/issues?q=" target="_blank">Search all issuees</a>.
- [X] I read <a href="https://github.com/ai-genie/vscode-chatgpt#troubleshooting" target="_blank">Troubleshooting guide on Readme</a> and there is not a guide on how to solve my problem.

### Describe the Bug

I hate to do this, but just couldnt stand it anymore. Seems like this project is dead.

With that said I've totally refactored the original extention to use the new OpenAI 4.0 beta, and best of all, implemented a GPT-Engineer type button to autonomously code. Yup!

Get it here, supports the 16k model, 32k, Azure and OpenAI.
https://marketplace.visualstudio.com/items?itemName=Autonimate.autonimate&ssr=false#review-details

### Please tell us if you have customized any of the extension settings or whether you are using the defaults.

Yes big time.

### Additional context

r

**Comment by gencay** [comment]
@Cytranics this isn't a new version.

@anyone else, If you want a more up-to-date extension or even selfhost your own extension check out my open-source project here. I have instructions on how to get it running locally without needing to download any extension for free: https://github.com/gencay/vscode-chatgpt. We will work on addressing the recent changes from OpenAI at some point, we just don't have enough time to do that.

**Comment by Cytranics** [comment]
This is your ext bud, I modified your code to work with the latest models. What's the issue?

Sent from Nine<http://www.9folders.com/>

________________________________
