### ISSUE TITLE
Please update it

### ISSUE THREAD

**Issue by PierrunoYT** [ai-genie/chatgpt-vscode#123]
### Verify it's not a duplicate bug report

- [X] I searched for similar bugs reported on GitHub and nobody has reported a similar issue. <a href="https://github.com/ai-genie/vscode-chatgpt/issues?q=" target="_blank">Search all issuees</a>.
- [X] I read <a href="https://github.com/ai-genie/vscode-chatgpt#troubleshooting" target="_blank">Troubleshooting guide on Readme</a> and there is not a guide on how to solve my problem.

### Describe the Bug

Please update it

### Please tell us if you have customized any of the extension settings or whether you are using the defaults.

Please update it

### Additional context

Please update it

**Comment by genieai-info** [comment]
Please check v0.0.9. The new models are available now.

**Comment by PierrunoYT** [comment]
Thx
