### ISSUE TITLE
All dates in changelog are in 2022 instead of 2023, and all are earlier than the release date of ChatGPT (Nov 30, 2022)

### ISSUE THREAD

**Issue by danysdragons** [ai-genie/chatgpt-vscode#125]
### Verify it's not a duplicate bug report

- [X] I searched for similar bugs reported on GitHub and nobody has reported a similar issue. <a href="https://github.com/ai-genie/vscode-chatgpt/issues?q=" target="_blank">Search all issuees</a>.
- [X] I read <a href="https://github.com/ai-genie/vscode-chatgpt#troubleshooting" target="_blank">Troubleshooting guide on Readme</a> and there is not a guide on how to solve my problem.

### Describe the Bug

View any entries in the changelog.

### Please tell us if you have customized any of the extension settings or whether you are using the defaults.

I have not made any customizations.

### Additional context

First changelog entry dated to March 20, 2022, but ChatGPT did not exist until November 2022:

![image](https://github.com/ai-genie/chatgpt-vscode/assets/40280395/32d6114a-6399-42f0-bdf8-10278af00526)

Most recent changelog entry:

![image](https://github.com/ai-genie/chatgpt-vscode/assets/40280395/d03f0f08-9ac4-4281-8393-9dcde635c190)

It seems likely that all dates in the changelog are exactly one year earlier than they should be.

**Comment by genieai-info** [comment]
Thank you. This is now fixed
