### ISSUE TITLE
api key invalid

### ISSUE THREAD

**Issue by salmasultana478** [ai-genie/chatgpt-vscode#126]
Type: <b>Bug</b>

it's showing api-key not valid , so i want to reset api key how can i do that?

Extension version: 0.0.8
VS Code version: Code 1.81.0 (6445d93c81ebe42c4cbd7a60712e0b17d9463e97, 2023-08-02T12:37:13.485Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by thuan1091996** [comment]
Search for "Genie: Clear API Key" in settings

**Comment by hey-jk** [comment]
I also got api key invalid.
I think genie is blocked from openai.

**Comment by robotaiguy** [comment]
Does Genie support environment variables, such as OPENAI_API_KEY ?

**Comment by Ansa211** [comment]
For me, this was not Genie's problem, it's a change in how the OpenAI API keys work. It used to be that you could use the API and you would pay at the end of the month. Now, you have to set up a balance in advance (at least 5 USD). Your invoices will then be deducted from the balance. If the balance goes to 0, or if you've never set it up, the API keys stop working.
