### ISSUE TITLE
Add all menu items inside one Genie menu

### ISSUE THREAD

**Issue by SergioSuarezDev** [ai-genie/chatgpt-vscode#127]
### Describe the feature

Add all genie menu items inside one Genie contenxt menu, to create a submenu of actions

Something like other plugins such as "Sort JSON"

<img width="550" alt="Captura de pantalla 2023-08-24 a las 16 34 26" src="https://github.com/ai-genie/chatgpt-vscode/assets/3636232/711e44f0-5f4c-4b88-a4e0-ad0fa46394de">

**Comment by SergioSuarezDev** [comment]
any comments?

**Comment by forumwt** [comment]
That's a good idea, I have already added for me that's feature 

![Screenshot 2023-09-28 150931](https://github.com/ai-genie/chatgpt-vscode/assets/16545063/3226c7b1-f115-46d6-a768-24d1698e051c)

**Comment by genieai-info** [comment]
@SergioSuarezDev This was a good suggestion. Now that people are more familiar with Genie and the abilities it provides, we agree that it makes sense to keep all under a sub menu. This is now released with v0.0.10 and all the context menu items are available under a sub menu. @amnweb fyi as well
