### ISSUE TITLE
Can't install extension because it is not compatible with the current version of Visual Studio Code (version 1.72.0)

### ISSUE THREAD

**Issue by Tokenizer94** [ai-genie/chatgpt-vscode#128]
### Verify it's not a duplicate bug report

- [X] I searched for similar bugs reported on GitHub and nobody has reported a similar issue. <a href="https://github.com/ai-genie/vscode-chatgpt/issues?q=" target="_blank">Search all issuees</a>.
- [X] I read <a href="https://github.com/ai-genie/vscode-chatgpt#troubleshooting" target="_blank">Troubleshooting guide on Readme</a> and there is not a guide on how to solve my problem.

### Describe the Bug

Can't install extension because it is not compatible with the current version of Visual Studio Code (version 1.72.0)

### Please tell us if you have customized any of the extension settings or whether you are using the defaults.

default

**Comment by genieai-info** [comment]
The lowest vscode version this extension requires is 1.73.0. Which is relatively still old, please consider upgrading your vscode.

**Comment by jiajieshidongjuncheng** [comment]
Can't install 'openai.chatgpt' extension because it is not compatible with the current version of Visual Studio Code(version 1.85.2)？？？？
