### ISSUE TITLE
Can I customize the text size?

### ISSUE THREAD

**Issue by chaos-zhu** [ai-genie/chatgpt-vscode#129]
### Describe the feature

It looks too big,It's not coordinated at all

![image](https://github.com/ai-genie/chatgpt-vscode/assets/44160914/31e09e85-1b38-4380-953f-5c31ce5e7e7e)

thx.

**Comment by mdrejhon** [comment]
You can use Ctrl-Plus and Ctrl-Minus to zoom in/out of text.  
It's synchronized with code size

**Comment by chaos-zhu** [comment]
> You can use Ctrl-Plus and Ctrl-Minus to zoom in/out of text. It's synchronized with code size. But a divergence setting (font size multiplier/divisor) would be nice.

thx
