### ISSUE TITLE
add `gpt-3.5-turbo-instruct` model option

### ISSUE THREAD

**Issue by gianpaj** [ai-genie/chatgpt-vscode#131]
### Describe the feature

https://openai.com/blog/gpt-3-5-turbo-fine-tuning-and-api-updates
https://platform.openai.com/docs/models/gpt-3-5

**Comment by Ansa211** [comment]
More generally, would be preferable if all currently available versions were automatically offered.

**Comment by genieai-info** [comment]
This is now available in the model selection
