### ISSUE TITLE
How can I shut down the stream generation?

### ISSUE THREAD

**Issue by wydy1601** [ai-genie/chatgpt-vscode#132]
### Verify it's not a duplicate bug report

- [X] I searched for similar bugs reported on GitHub and nobody has reported a similar issue. <a href="https://github.com/ai-genie/vscode-chatgpt/issues?q=" target="_blank">Search all issuees</a>.
- [X] I read <a href="https://github.com/ai-genie/vscode-chatgpt#troubleshooting" target="_blank">Troubleshooting guide on Readme</a> and there is not a guide on how to solve my problem.

### Describe the Bug

HTTP 400 Bad Request. You may have exhausted your OpenAI subscription allowance or have an expired account. You can clear your API Key from VS Code's [secrets storage](https://code.visualstudio.com/api/references/vscode-api#SecretStorage) with Genie: Clear API Key command. Check your allowance and account's expiration date here: https://platform.openai.com/account/usage

                    {
                        "message": "Streaming completion is not support yet, please remove 'stream' key value in the request payload."
                    }

I got the message above, but I don't know how to set stream=False. There is no way for me to change the request payload.

### Please tell us if you have customized any of the extension settings or whether you are using the defaults.

I enter my own Azure API, and it doesn't support stream.

**Comment by genieai-info** [comment]
Could you make sure that you are providing the correct url for your azure deployment? It should look like this "https://your-endpoint-base.openai.azure.com/openai/deployments/your-azure-model-name/completions?api-version=2022-12-01". And if you provide the right url, then it shouldn't try to stream.
