### ISSUE TITLE
Please consider open-sourcing this extension if you're no longer able to maintain it

### ISSUE THREAD

**Issue by cahaseler** [ai-genie/chatgpt-vscode#137]
### Describe the feature

Hi,

It seems like this extension is essentially abandoned, but quite a few people still think it's one of the best choices out there. I understand some projects can't be supported forever, but if you'd consider open sourcing it, I'm sure the community would try to keep maintaining it. As more features are added to the openAI APIs, there will be more demand for adding support for things like the new 128k api.

**Comment by genieai-info** [comment]
Hi there - the open source version is here https://github.com/gencay/vscode-chatgpt. Which lacks a few features that we implemented.

We finally released a new version that support all the new cool models from OpenAI. Please give it a try

**Comment by cahaseler** [comment]
Thanks for the quick response and the update! Appreciate the effort!
