### ISSUE TITLE
Support rendering LaTeX in Genie's response

### ISSUE THREAD

**Issue by leesq01** [ai-genie/chatgpt-vscode#14]
### Verify it's not a duplicate bug report

- [X] I searched for similar bugs reported on GitHub and nobody has reported a similar issue. <a href="https://github.com/ai-genie/vscode-chatgpt/issues?q=" target="_blank">Search all issuees</a>.
- [X] I read <a href="https://github.com/ai-genie/vscode-chatgpt#troubleshooting" target="_blank">Troubleshooting guide on Readme</a> and there is not a guide on how to solve my problem.

### Describe the Bug

Markdown or LaTeX(I don't know which causes the issue) formatted text is not rendered in Conversation view.

-window11
-vscode(version 1.76.2)

### Please tell us if you have customized any of the extension settings or whether you are using the defaults.

using the defaults

### Additional context

![Snipaste_2023-03-23_13-48-40](https://user-images.githubusercontent.com/63660880/227115180-f0f36c6f-2f68-4373-94bf-e585a33938ef.jpg)

**Comment by genieai-info** [comment]
The extension doesn't render Latex, only Markdown. If you copy the response in Markdown, you will see the ChatGPT's raw response. as far as I can see, everything in your screenshot looks fine. Could you provide us with your prompt in English and the response you are getting?

**Comment by leesq01** [comment]
> The extension doesn't render Latex, only Markdown. If you copy the response in Markdown, you will see the ChatGPT's raw response. as far as I can see, everything in your screenshot looks fine. Could you provide us with your prompt in English and the response you are getting?

my prompt in English is: show me some examples of latex formula

the response
好的，以下是一些常用的latex公式示例 is  Ok, here are some examples of commonly used latex formulas
代码 is code ，显示 is display
as you said, there's no problem in Markdown, but Latex.
maybe render Latex is a good idea

**Comment by genieai-info** [comment]
Thanks for confirming. I updated the label of this to be enhancement and removed the bug label.

Our focus is to bring the extension to a level to provide users with the best experience with AI. Rendering LaTeX is out of scope at the moment. However, we are happy to see whether this enhancement request is a popular one.

If you stumbled upon this issue in the future, please upvote this comment if you want us to consider adding a LaTeX rendering support in the upcoming releases.

**Comment by RobertAlbus** [comment]
@genieai-info what is the best way to indicate support for this feature request?
