### ISSUE TITLE
Custom model name support

### ISSUE THREAD

**Issue by ShinChven** [ai-genie/chatgpt-vscode#146]
### Describe the feature

I want to use a custom model, but I can't find a way to set the model name. Please support and provide an input in the configuration to add a custom model name.

For instance, I use [one-api](https://github.com/songquanpeng/one-api) as the provider, which enables me to utilize `gemini-pro` in the OpenAI API protocol.

**Comment by zhangtony239** [comment]
me too!

**Comment by genieai-info** [comment]
Custom model name can be added via your Settings.JSON. Tou can ignore the warning if it's not recognized as part of the predefined enum models. Just overwrite the setting `genieai.openai.model` with your preferred openai model name
