### ISSUE TITLE
 how to change the default system message in prompt.  

### ISSUE THREAD

**Issue by jeffery9** [ai-genie/chatgpt-vscode#149]
### Describe the feature

want to change the default system message

**Comment by agn-7** [comment]
Is it possible to change or append a `system` message prompt to the LLM? For example, I want to add "You are not allowed to generate response more than one paragraph within the system message prompt . . ."

I found two custom prompts within the settings of Genie in vscode, but despite the fact that I enabled them, it doesn't work!

**Comment by genieai-info** [comment]
Added a new setting `genieai.systemMessage` to customize the initial system message in the new version v0.0.12

https://github.com/ai-genie/chatgpt-vscode/releases/tag/v0.0.12

**Comment by agn-7** [comment]
> Added a new setting `genieai.systemMessage` to customize the initial system message in the new version v0.0.12

Thanks a lot for the update. 

BTW, the OpenAI new model `o1` doesn't support the `system` role and some parameters like `max_tokens`, `temperature`, `stream`, etc.
