### ISSUE TITLE
keep telling me that "text-davinci-003" is not availed

### ISSUE THREAD

**Issue by florin159** [ai-genie/chatgpt-vscode#155]
### Verify it's not a duplicate bug report

- [X] I searched for similar bugs reported on GitHub and nobody has reported a similar issue. <a href="https://github.com/ai-genie/vscode-chatgpt/issues?q=" target="_blank">Search all issuees</a>.
- [X] I read <a href="https://github.com/ai-genie/vscode-chatgpt#troubleshooting" target="_blank">Troubleshooting guide on Readme</a> and there is not a guide on how to solve my problem.

### Describe the Bug

I was using it some time ago with no problem, but is something odd that is happening now.
When I select a part of the code that I want to improve/test has opened a new window (in stead should give me explanations of what I ask)
"An error occured. ChatGPT error 404: { "error": { "message": "The model `text-davinci-003` has been deprecated, learn more here: https://platform.openai.com/docs/deprecations", "type": "invalid_request_error", "param": null, "code": "model_not_found" } }"

But also in the bottom right corner is pop this error 
is say that is selected 'text-davinci-003'" and is keep saying same error even when try to select diferent models from setings.

Is say that is selected 'text-davinci-003' and is keep saying same error even when try to select different models from settings.
Let me know what information I can bring to find the problem
PS the chat window is working with noprolems...
Thx:)

### Please tell us if you have customized any of the extension settings or whether you are using the defaults.

0 costumize

### Additional context

![image](https://github.com/ai-genie/chatgpt-vscode/assets/62816566/d8cc832d-8a65-45a5-9c4c-2cf3c122537a)

**Comment by florin159** [comment]
> +1 Same here, whatever model I select, the same API error appears about `text-davinci-003` not being available. Makes the entire extension unusable.

is usable but only in the normal chat from left, not when you want to select the code by highlighting.

**Comment by gertjanjansen** [comment]
+1 Same here. I can't use the extension because of this error. I keep seeing this error while I haven't configured text-davinci-003 anywhere

<img width="455" alt="Screenshot 2024-02-28 at 10 05 23" src="https://github.com/ai-genie/chatgpt-vscode/assets/1429089/6c275a0f-bfda-4576-8322-6c3d10dc8ca9">

**Comment by philip-denys** [comment]
+1 same here
uninstalling the ext

**Comment by moltra** [comment]
I am getting the following error.  I did not start a new topic since my error is related to text-davinici-003

`An error occured. ChatGPT error 404: { "error": { "message": "The model `text-davinci-003` has been deprecated, learn more here: https://platform.openai.com/docs/deprecations", "type": "invalid_request_error", "param": null, "code": "model_not_found" } }`

**Comment by Ereiqat** [comment]
I've the same error here, did you manage to solve it?

**Comment by CS06** [comment]
Same.  Just installed the extension and can't get passed this issue.

**Comment by genieai-info** [comment]
@CS06 when you just installed the extension for the first time it should welcome you with the Conversation View which uses gpt4 model by default - not text-davinci. So if you encountered this issue as a brand-new user it sounds like a bug on our end. Could you elaborate on your experience a little bit?


For everyone the Editor View is now fixed and it uses your preferred model just like in the Conversation View.
