### ISSUE TITLE
Add the gpt-4-0125-preview and gpt-4-turbo-preview models.

### ISSUE THREAD

**Issue by bituq** [ai-genie/chatgpt-vscode#156]
### Describe the feature

Add the recently released `gpt-4-0125-preview` and `gpt-4-turbo-preview` to the list of models.

https://platform.openai.com/docs/models/gpt-4-and-gpt-4-turbo

**Comment by wellmorq** [comment]
Bump!

**Comment by SHSharkar** [comment]
I also want to provide a plus vote from my end.

Recently, several new models have been added to the **OpenAI API**, but in **Genie AI** settings, we cannot use the latest OpenAI API models. It would be nice to have the functionality to use it.

In the settings, if we add the latest model names, we get the following warning:

> **The value is not accepted, and then a list of valid values were given.**

If I override the values in the new OpenAI model name and then try to generate a git commit, I get the following error:

> **An error occured. ChatGPT error 400: Unsupported data type**

![image](https://github.com/ai-genie/chatgpt-vscode/assets/12555542/aadf2f53-c92c-48e6-9b14-97deeab7e40b)

**Comment by philletourneau** [comment]
Really looking forward to this model being added!

**Comment by busseyl** [comment]
+1

**Comment by liumengdi** [comment]
+1

**Comment by xmjiao** [comment]
Since new models are being added by OpenAI continuously, it would be great if a user is allowed to type a model name manually beside selecting from a list of known models.

**Comment by austin-millan** [comment]
`gpt-4-turbo-2024-04-09` came out today (see: https://platform.openai.com/docs/models/overview), yet can't use this model with Genie, even when overriding `genieai.openai.model` in `settings.json`. Users should be able to override.

**Comment by star-rbx** [comment]
^ Can any admin take a look on this ticket! We really need the field to be customizable

**Comment by wellmorq** [comment]
Looks like the repo isn't supported any more. So, I switched to Continue.dev - smth like this tool.

**Comment by genieai-info** [comment]
The extension is updated with the newest OpenAI models please update to v0.0.11
