### ISSUE TITLE
How can I apply mu open ai key for genie , There is no option any setting . Could anyone please help me 

### ISSUE THREAD

**Issue by shobhitagnihotri69** [ai-genie/chatgpt-vscode#159]
### Describe the feature

I want a feature where I can apply my open ai key easily . There is no option available on setting.

**Comment by genieai-info** [comment]
Use Change API Key in the home menu of the Conversation View. You can switch between the views by clicking this button here:

![image](https://github.com/ai-genie/chatgpt-vscode/assets/128560534/6342aa06-73b0-4d6c-a6b5-e0f64efe1fb6)


Change API Key

![image](https://github.com/ai-genie/chatgpt-vscode/assets/128560534/4ff42925-ef0e-4462-a168-11eefd192581)
