### ISSUE TITLE
Lagging with responses - User aborted a request

### ISSUE THREAD

**Issue by icycoldveins** [ai-genie/chatgpt-vscode#16]
### Verify it's not a duplicate bug report

- [X] I searched for similar bugs reported on GitHub and nobody has reported a similar issue. <a href="https://github.com/ai-genie/vscode-chatgpt/issues?q=" target="_blank">Search all issuees</a>.
- [X] I read <a href="https://github.com/ai-genie/vscode-chatgpt#troubleshooting" target="_blank">Troubleshooting guide on Readme</a> and there is not a guide on how to solve my problem.

### Describe the Bug

When asking the ai a question it has a tendency to lag and will often times require the user to refresh the conversation or stop the ai manually and ask again in order to get a response again 

### Please tell us if you have customized any of the extension settings or whether you are using the defaults.

No customizations

**Comment by genieai-info** [comment]
There have been known issues with OpenAI latency lately/throughout last week. You may have experienced it during the down/slow times of the OpenAI services. Unfortunately, it's out of this extension's capability to fix that. In these cases, usually stopping the request via Stop responding button and re-sending your prompt solves the issue after a few tries.
