### ISSUE TITLE
Unable to activate API key

### ISSUE THREAD

**Issue by Ereiqat** [ai-genie/chatgpt-vscode#166]
### Verify it's not a duplicate bug report

- [X] I searched for similar bugs reported on GitHub and nobody has reported a similar issue. <a href="https://github.com/ai-genie/vscode-chatgpt/issues?q=" target="_blank">Search all issuees</a>.
- [X] I read <a href="https://github.com/ai-genie/vscode-chatgpt#troubleshooting" target="_blank">Troubleshooting guide on Readme</a> and there is not a guide on how to solve my problem.

### Describe the Bug

Hello,
I've been experiencing an issue with the ChatGPT Genie AI where I receive a 404 Not Found error whenever I input the API key to try to use the extension with different model identifiers, including gpt-4 and gpt-3.5-turbo.

I have chatgpt plus subscription and still it doesn't work

### Please tell us if you have customized any of the extension settings or whether you are using the defaults.

I tried to change the model, but it still gives me error 404

**Comment by djalexnl** [comment]
Same Issue Here, does anyone have a solution for this?

**Comment by coachdesign** [comment]
same issue

**Comment by junjunmeng** [comment]
same issue

**Comment by Ludenser** [comment]
same

**Comment by bvitlas** [comment]
same
