### ISSUE TITLE
Add GPT-4o

### ISSUE THREAD

**Issue by danielorozco06** [ai-genie/chatgpt-vscode#167]
### Describe the feature

Add the recently released GPT-4o to the list of models https://openai.com/index/hello-gpt-4o/

**Comment by IlmariKu** [comment]
I was hoping for the same, but I think this repo has been abandoned and we just have to move to something different.

**Comment by agn-7** [comment]
Does someone know any extension equivalent to Genie?

**Comment by slazak** [comment]
> I was hoping for the same, but I think this repo has been abandoned and we just have to move to something different.

That would be seed. I truly appreciate this extension and discovered it to be a better fit for me than Copilot.

**Comment by ChuckJonas** [comment]
> I was hoping for the same, but I think this repo has been abandoned and we just have to move to something different.

Not to mention, it was never open source in the first place... Would love to see a community driven version of this.

**Comment by ClicBizDev** [comment]
Go to C:\Users\[your username]\.vscode\extensions\genieai.chatgpt-vscode-0.0.10\ and edit package.json by replacing in genieai.openai.model "gpt-4" by "gpt-4o"

Then goto the \out folder and edit extension.js:
Update this line, replacing gpt-4 option by gpt-4o:
var Q1={"gpt-4-1106-preview":{maxTokens:8192,version:"gpt-4",type:"chat"},"**gpt-4o**":{maxTokens:8192,version:"gpt-4",type:"chat"},"gpt-4-32k":{maxTokens:32768,version:"gpt-4",type:"chat"},"gpt-4-0613":{maxTokens:8192,version:"gpt-4",type:"chat"},"gpt-4-32k-0613":{maxTokens:32768,version:"gpt-4",type:"chat"},"gpt-3.5-turbo-1106":{maxTokens:4096,version:"gpt-3.5",type:"chat"},"gpt-3.5-turbo":{maxTokens:4096,version:"gpt-3.5",type:"chat"},"gpt-3.5-turbo-16k":{maxTokens:4096,version:"gpt-3.5",type:"chat"},"gpt-3.5-turbo-instruct":{maxTokens:4096,version:"gpt-3.5",type:"chat"},"text-davinci-003":{maxTokens:4096,version:"gpt-3.5",type:"text"},"text-davinci-002":{maxTokens:4096,version:"gpt-3.5",type:"text"},"text-curie-001":{maxTokens:2048,version:"gpt-3",type:"text"},"text-babbage-001":{maxTokens:2048,version:"gpt-3",type:"text"},"text-ada-001":{maxTokens:2048,version:"gpt-3",type:"text"},"code-davinci-002":{maxTokens:8001,version:"gpt-3.5",type:"codex"},"code-cushman-002":{maxTokens:2048,version:"gpt-3",type:"codex"}},lo="gpt-4-1106-preview";

Then deactivate and reactivate the extension, go to settings and update the model. And enjoy!

**Comment by Ansa211** [comment]
> "**gpt-4o**":{maxTokens:8192,version:"gpt-4",type:"chat"},

shouldn't it be `version: "gpt-4o"` as well?

**Comment by agn-7** [comment]
> > "**gpt-4o**":{maxTokens:8192,version:"gpt-4",type:"chat"},
> 
> shouldn't it be `version: "gpt-4o"` as well?

No

**Comment by ilham-fetchly** [comment]
> Go to C:\Users[your username].vscode\extensions\genieai.chatgpt-vscode-0.0.10\ and edit package.json by replacing in genieai.openai.model "gpt-4" by "gpt-4o"
> 
> Then goto the \out folder and edit extension.js: Update this line, replacing gpt-4 option by gpt-4o: var Q1={"gpt-4-1106-preview":{maxTokens:8192,version:"gpt-4",type:"chat"},"**gpt-4o**":{maxTokens:8192,version:"gpt-4",type:"chat"},"gpt-4-32k":{maxTokens:32768,version:"gpt-4",type:"chat"},"gpt-4-0613":{maxTokens:8192,version:"gpt-4",type:"chat"},"gpt-4-32k-0613":{maxTokens:32768,version:"gpt-4",type:"chat"},"gpt-3.5-turbo-1106":{maxTokens:4096,version:"gpt-3.5",type:"chat"},"gpt-3.5-turbo":{maxTokens:4096,version:"gpt-3.5",type:"chat"},"gpt-3.5-turbo-16k":{maxTokens:4096,version:"gpt-3.5",type:"chat"},"gpt-3.5-turbo-instruct":{maxTokens:4096,version:"gpt-3.5",type:"chat"},"text-davinci-003":{maxTokens:4096,version:"gpt-3.5",type:"text"},"text-davinci-002":{maxTokens:4096,version:"gpt-3.5",type:"text"},"text-curie-001":{maxTokens:2048,version:"gpt-3",type:"text"},"text-babbage-001":{maxTokens:2048,version:"gpt-3",type:"text"},"text-ada-001":{maxTokens:2048,version:"gpt-3",type:"text"},"code-davinci-002":{maxTokens:8001,version:"gpt-3.5",type:"codex"},"code-cushman-002":{maxTokens:2048,version:"gpt-3",type:"codex"}},lo="gpt-4-1106-preview";
> 
> Then deactivate and reactivate the extension, go to settings and update the model. And enjoy!

I use a different approach for this:
instead of change the gpt-4 to gpt-4o, I added this `"gpt-4o":{maxTokens:8192,version:"gpt-4",type:"chat"},"gpt-4o-2024-05-13":{maxTokens:8192,version:"gpt-4",type:"chat"},` before "gpt-4-1106-preview" then on package.json on "genieai.openai.model" I also added two new models: "gpt-4o" and "gpt-4o-2024-05-13" related to what I added on extension.js

**Comment by ClicBizDev** [comment]
Congrat, it's cleaner than what I did :-)

**Comment by genieai-info** [comment]
Hi everyone - The new models are now available in v0.0.11 please update your extensions. gpt-4o is set as default. The editor view issue is also fixed and now it uses your selected model instead of the deprecated legacy OpenAI model.

**Comment by IlmariKu** [comment]
Oh wow, thanks for coming back to the extension @genieai-info ! I've loved to use the extension, good to see I don't have to switch over to anything else.
