### ISSUE TITLE
新key一直提示额度用尽怎么回事？

### ISSUE THREAD

**Issue by 780853199** [ai-genie/chatgpt-vscode#169]
### Describe the feature

![image](https://github.com/ai-genie/chatgpt-vscode/assets/72066390/a898c56b-fc21-47d2-9ccf-faf6e1fa5d7a)

**Comment by 780853199** [comment]
明明我看来openai的额度都没有用，怎么提示额度用尽？

**Comment by genieai-info** [comment]
Can you explain your issue in English please, I don't speak that language..

The error 429 may mean that you don't have any credit left on openai side, you should purchase/add credit to your openai account and create the api key to use your credit.
