### ISSUE TITLE
[FEATURE REQUEST] Prefix for ad hoc prompt

### ISSUE THREAD

**Issue by erkkimon** [ai-genie/chatgpt-vscode#184]
### Describe the feature

BACKGROUND

Especially GPT-4o very eagerly rewrites all code when asked to do a small change using ad hoc prompt. This is problematic, because it wastes time, tokens and also makes it difficult to spot the lines that should be changed. That's why I always need to remember to use my life to write something like "Don't give me full edited code, just the edited lines."

SOLUTION

The most straightforward and versatile solution would be making it possible to add prefix also for ad hoc prompts.

**Comment by genieai-info** [comment]
Added a new setting `genieai.systemMessage` to customize the initial system message in the new version v0.0.12

https://github.com/ai-genie/chatgpt-vscode/releases/tag/v0.0.12

**Comment by erkkimon** [comment]
@genieai-info Wonderful, thank you!
