### ISSUE TITLE
GPT-o1 support

### ISSUE THREAD

**Issue by IlmariKu** [ai-genie/chatgpt-vscode#185]
### Describe the feature

OpenAI just released new o1-model. Could we get the support of it added to Genie?

https://openai.com/index/introducing-openai-o1-preview/

**Comment by genieai-info** [comment]
Added support for the new models in the v0.0.12. However, **Please note that these new models have usage tier limitations. See [Usage tiers](https://platform.openai.com/docs/guides/rate-limits/usage-tiers).**

For the future reference, you can always overwrite the `genieai.openai.model` manually in your settings.json. You can ignore the warning that it will show if the new model you are adding isn't part of the enum

**Comment by IlmariKu** [comment]
Thanks @genieai-info for the PR and anyways the fix!

I didn't know that. We have an API-wrapper, so we could have used any model-name from the menu and fix our middle-layer to use the o1, which I was planning to do.
