### ISSUE TITLE
support bowser API

### ISSUE THREAD

**Issue by baranwang** [ai-genie/chatgpt-vscode#2]
### Describe the feature

support bowser API

**Comment by genieai-info** [comment]
Hi @baranwang we will not add a support to use Browser to the extension unfortunately due to potential ToS issues users may face. The only available way to use the extension is API Key at the moment.

**Comment by nico-medellin** [comment]
Do we have to have a paid plan to use Open AI's API key? @genieai-info

**Comment by genieai-info** [comment]
You can get your API Key by creating an account here: https://platform.openai.com/account/api-keys. If you exhausted your initial credit, or have an expired account, yes you probably need to pay to get access to it.

**Comment by UniqueName12345** [comment]
> You can get your API Key by creating an account here: https://platform.openai.com/account/api-keys. If you exhausted your initial credit, or have an expired account, yes you probably need to pay to get access to it.
Well, that sucks.
