### ISSUE TITLE
Can't enter API key - No notification is shown due to vs code's do not disturb mode

### ISSUE THREAD

**Issue by MarcelSchwegler** [ai-genie/chatgpt-vscode#30]
### Verify it's not a duplicate bug report

- [X] I searched for similar bugs reported on GitHub and nobody has reported a similar issue. <a href="https://github.com/ai-genie/vscode-chatgpt/issues?q=" target="_blank">Search all issuees</a>.
- [X] I read <a href="https://github.com/ai-genie/vscode-chatgpt#troubleshooting" target="_blank">Troubleshooting guide on Readme</a> and there is not a guide on how to solve my problem.

### Describe the Bug

I just installed the extension and I'm unable to enter an API key as no prompt comes up. I tried asking questions multiple times, but nothing happens as I click on the ask button. I tried all types of prompts you supply with the extension. I restarted VSCode, reinstalled the extension and restarted my Windows 11 machine, no change. I tried the "Reset Session" and "Clear API Key" but nothing happens at all when I click them. I tried if I can do a request via curl with my API key and that works fine.
I'm just unable to enter the API key.

### Please tell us if you have customized any of the extension settings or whether you are using the defaults.

I didn't change any of the default settings.

**Comment by genieai-info** [comment]
Hi @MarcelSchwegler - You should be seeing a notification bottom top - click notification bell icon to see your notifications:

![image](https://user-images.githubusercontent.com/128560534/227905401-ed99cc25-79a7-45ad-bade-1adace03167d.png)

Let us know if you aren't seeing it. Also what's your OS type(mac/win/linux) and version?

**Comment by MarcelSchwegler** [comment]
Hi @genieai-info - Somehow VSCode was in a not disturb mode. I didn't even know that such thing exists. After deactivation of this mode, I was able to find the API prompt and everything is working now 😀 
Thank you!

**Comment by genieai-info** [comment]
You're welcome, since this confused you and possibly other users, we are planning to improve this user experience. Thank you for bringing it up!
