### ISSUE TITLE
Prefill Git commit message with meaningful msg following conventional commits

### ISSUE THREAD

**Issue by hoegertn** [ai-genie/chatgpt-vscode#32]
### Describe the feature

It would be cool to start a git commit with an auto-generated message. Currently I am doing this manually using chatGPT UI but would be nice to send the diff and a prompt to the API and prefill the commit message.

**Comment by genieai-info** [comment]
@hoegertn this sounds great. Are you using Terminal to write your git commits? We couldn't find a vscode contribution point for Terminal page. We added support for Problems just today to enable Genie to `Quick Fix compile-time errors`. However, Terminal doesn't have a right click context menu enabled, I think. Let us know if you have any ideas how you would go about implementing this

**Comment by genieai-info** [comment]
@hoegertn this is now available in v0.0.10. Please check out our changelog and let us know if you have any feedback
