### ISSUE TITLE
Request to https://api.openai.com/v1/chat/completions failed, reason: certificate has expired

### ISSUE THREAD

**Issue by gforien** [ai-genie/chatgpt-vscode#36]
### Verify it's not a duplicate bug report

- [X] I searched for similar bugs reported on GitHub and nobody has reported a similar issue. <a href="https://github.com/ai-genie/vscode-chatgpt/issues?q=" target="_blank">Search all issuees</a>.
- [X] I read <a href="https://github.com/ai-genie/vscode-chatgpt#troubleshooting" target="_blank">Troubleshooting guide on Readme</a> and there is not a guide on how to solve my problem.

### Describe the Bug

- Open the extension
- Ask any question

```
Request to https://api.openai.com/v1/chat/completions failed, reason: certificate has expired
```

<img width="200" alt="image" src="https://user-images.githubusercontent.com/7701186/228273631-2c36a1ee-25b8-4af0-8d5e-9fb0bbfd0fe7.png">

- When disabling cert verification in VSCode with `"http.systemCertificates": false,`, the API call works again.

### Please tell us if you have customized any of the extension settings or whether you are using the defaults.

No

### Additional context
<details>
<summary>Details</summary>

The OpenAI API does not seem to have certificate problems.
```
❯ curl https://api.openai.com/v1/chat/completions \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $OPENAI_API_KEY" \
  -d '{
     "model": "gpt-3.5-turbo",
     "messages": [{"role": "user", "content": "Say this is a test!"}],
     "temperature": 0.7
   }' -v
...
* (304) (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / AEAD-AES256-GCM-SHA384
* ALPN: server accepted h2
* Server certificate:
*  subject: CN=api.openai.com
*  start date: Jan 28 00:46:58 2023 GMT
*  expire date: Apr 28 00:46:57 2023 GMT
*  subjectAltName: host "api.openai.com" matched cert's "api.openai.com"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
...

{"id":"xxxxxxxxxx","object":"chat.completion","created":xxxxxxxx,"model":"gpt-3.5-turbo-0301","usage":{"prompt_tokens":14,"completion_tokens":5,"total_tokens":19},"choices":[{"message":{"role":"assistant","content":"This is a test!"},"finish_reason":"stop","index":0}]}
```

VSCode updated to last version
```
Version: 1.76.2
Commit: ee2b180d582a7f601fa6ecfdad8d9fd269ab1884
Date: 2023-03-14T17:54:09.061Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin x64 22.3.0
Sandboxed: Yes
```

</details>

**Comment by genieai-info** [comment]
@gforien this is related to vscode (electron) and your machine's certificate storage. Could you try removing your expired certs from your machine's trusted cert store as suggested here: https://github.com/microsoft/vscode/issues/97434

Could also be related to your self-signed certs in the store. Found a few more hits on stackoverflow like this: https://stackoverflow.com/questions/71477345/how-to-figure-out-why-vs-code-considers-the-certificate-expired-whereas-it-is-no

Either cleaning up your trusted store or updating your vscode settings as you tried are our only suggestions for this error.

**Comment by gforien** [comment]
Thank you. [This comment](https://github.com/microsoft/vscode/issues/97434#issuecomment-812094349) solved it for me

**Comment by maruciprian99** [comment]
@gforien i have same issue, can you help me to fix it? i didn`t know how

**Comment by gforien** [comment]
What in the detailed steps did not work for you ?

> 1. Open up Keychain Access
> 2. View > Show Expired Certificates
> ...

**Comment by maruciprian99** [comment]
https://github.com/ai-genie/chatgpt-vscode/issues/89 @gforien 
i put here my error, its a bit different than yours, its happened suddenly
