### ISSUE TITLE
How do I change my API key

### ISSUE THREAD

**Issue by CameronRWest** [ai-genie/chatgpt-vscode#37]
### Verify it's not a duplicate bug report

- [X] I searched for similar bugs reported on GitHub and nobody has reported a similar issue. <a href="https://github.com/ai-genie/vscode-chatgpt/issues?q=" target="_blank">Search all issuees</a>.
- [X] I read <a href="https://github.com/ai-genie/vscode-chatgpt#troubleshooting" target="_blank">Troubleshooting guide on Readme</a> and there is not a guide on how to solve my problem.

### Describe the Bug

I entered the wrong API key by mistake. But now I can't seem to find where you're supposed to change that. i don't see a setting anywhere in extension settings to change. 

### Please tell us if you have customized any of the extension settings or whether you are using the defaults.

no

**Comment by PierrunoYT** [comment]
Check this 

![grafik](https://user-images.githubusercontent.com/95778421/229108388-3a689f2e-ac56-4451-bd4b-94a5352d3c27.png)

**Comment by genieai-info** [comment]
You can clear your API Key via `Genie: Clear API Key` command. You could also view all commands available click on the more menu button in the text box, select `> See commands`

We rolled out a change to make it more explicit. You can change the API Key from home page now as well as via Command palette.

Please update your extension to v0.0.5
![image](https://user-images.githubusercontent.com/128560534/229109647-0ac34519-a5f2-4049-978b-90a134174a11.png)

**Comment by CameronRWest** [comment]
> Check this
> 
> ![grafik](https://user-images.githubusercontent.com/95778421/229108388-3a689f2e-ac56-4451-bd4b-94a5352d3c27.png)

I tried looking in there, no setting for API keys

**Comment by CameronRWest** [comment]
> 

Ah I see, i was not in conversation view. I was in editor view. Could we get that added to editor view as well?
