### ISSUE TITLE
Change API Key button function inactive/Genie not running requests

### ISSUE THREAD

**Issue by emrecoding** [ai-genie/chatgpt-vscode#42]
### Verify it's not a duplicate bug report

- [X] I searched for similar bugs reported on GitHub and nobody has reported a similar issue. <a href="https://github.com/ai-genie/vscode-chatgpt/issues?q=" target="_blank">Search all issuees</a>.
- [X] I read <a href="https://github.com/ai-genie/vscode-chatgpt#troubleshooting" target="_blank">Troubleshooting guide on Readme</a> and there is not a guide on how to solve my problem.

### Describe the Bug

- The Change API Key button is not functioning. 
- Requests are not being run in Genie. I will type a response up and send it through, the response does not seem to process and the text that I enter disappears after I hit the 'enter'. 

- *ATTENTION* -------- This seems to be the case only while using VScode on MacOs* On windows operating system, same issue is not duplicating.

### Please tell us if you have customized any of the extension settings or whether you are using the defaults.

I was using gpt-3.5-turbo the day before I was unable to run any requests using Genie:ChatGPT through VSCode.

**Comment by pentago** [comment]
same here, constantly complaints about missing API key.

**Comment by genieai-info** [comment]
@emrecoding @pentago We have added a `Change API Key` on the home page now for you to clear/update your API Keys directly. Though there has always been command `Genie: Clear API Key` that you could use via vscode's command palette, or via the more button in the chat window (`> See commands`)

@emrecoding about your 2nd question are you facing a similar issue like the one reported here: #11 ?

**Comment by emrecoding** [comment]
@genieai-info using the command seemed to resolve the issue. I cleared the API Key using the command palette, then created a new key from openai. Clearing the API Key using the command palette brought back function to the 'Change API Key' button on the home screen on Genie. 

As for the second issue, that is exactly what I was referring to. When the 'Change API Key' was non-functional, the same issue as described in #11 was duplicating on my end.

**Comment by genieai-info** [comment]
@emrecoding do you possibly have copilot installed like the other report? It'd  be actually useful if you could check  out the developer view and see if there are any reported console errors. You can open the developer view of vs code using the command like:

![image](https://user-images.githubusercontent.com/128560534/229386056-51426150-3f34-4859-8156-23a23edd53a7.png)

**Comment by Msameim181** [comment]
After changing the API Key, It does not work for me. No conversation, No editor. And there is no console log relevant to this issue.
