### ISSUE TITLE
[Feat] Support Azure OpenAI Service

### ISSUE THREAD

**Issue by jhhuang96** [ai-genie/chatgpt-vscode#50]
Azure OpenAI Service provides REST API access to OpenAI's powerful language models including the GPT-3, Codex and Embeddings model series. ([link](https://learn.microsoft.com/en-us/azure/cognitive-services/openai/overview))

Azure OpenAI Service gives customers advanced language AI with OpenAI GPT-4, GPT-3, Codex, and DALL-E models with the security and enterprise promise of Azure. Azure OpenAI co-develops the APIs with OpenAI, ensuring compatibility and a smooth transition from one to the other.

With Azure OpenAI, customers get the security capabilities of Microsoft Azure while running the same models as OpenAI. Azure OpenAI offers private networking, regional availability, and responsible AI content filtering.

**Comment by jhhuang96** [comment]
Cool, I found the latest version (v0.0.7) already support Azure URL. However, when I filled the field and try to repeat clear/set API key, it still said the HTTP 400 error. 

![image](https://user-images.githubusercontent.com/17799955/229458439-02fd978a-60e1-4608-9ce1-206d7a448bf7.png)

BTW, the API key below is general for both OpenAI and Azure OpenAI?

![image](https://user-images.githubusercontent.com/17799955/229458781-285705a6-d54f-463a-8317-e488bf49b118.png)

**Comment by genieai-info** [comment]
@jhhuang96 thank you for opening this issue. We have a Readme section regarding this error. Please make sure you are selecting the correct base model that you used to create your Azure OpenAI service. So if your Azure model is a chat model, you can select gpt-3.5 OR if your Azure model is based off of a GPT-3 (Text-Davinci-*) model then make sure to select text-davinci-003. Below is the FAQ section on our [readme](https://github.com/ai-genie/chatgpt-vscode#faq):

> Azure OpenAI Service: Unsupported data type Error: This means you didn't select the right base model for your Azure OpenAI service. Make sure to select the base GPT model you used to create your Azure OpenAI Service deployment

**Comment by jhhuang96** [comment]
Hi @genieai-info , thanks for your reply. It is weird that I chose and deployed GPT-3.5 Turbo model in Azure. But in your extension, only chose "Text-Davinci-003" that can work.

![image](https://user-images.githubusercontent.com/17799955/229725776-cd88649b-ea19-4392-adb2-36c3e584c19d.png)

![image](https://user-images.githubusercontent.com/17799955/229731202-fc292bc8-d2f6-49f4-b2e9-9ba4cb17f86e.png)

**Comment by bajinsheng** [comment]
I have the exactly same issue.
It only work when I choose Text-Dvainci-003, while I deployed GPT-3.5 turbo

**Comment by bajinsheng** [comment]
![image](https://user-images.githubusercontent.com/10702191/229989624-0065a9eb-7b71-4f3a-b260-5a0643021d7a.png)

Even if it looks like working, but a bit gibberish

**Comment by jhhuang96** [comment]
FYI @gencay

**Comment by genieai-info** [comment]
Please make sure you are using the right completion endpoints for your azure openai deployments. Notice that if you're using a chat endpoint it needs to have `/chat` in your url. Please check out this comment: https://github.com/ai-genie/chatgpt-vscode/issues/66#issuecomment-1508023353
