### ISSUE TITLE
Quick fix - option to reorder or opt out.

### ISSUE THREAD

**Issue by BuckAMayzing** [ai-genie/chatgpt-vscode#54]
### Describe the feature

For code that has an error, Genie takes the top spot in the quick fix menu. For a significant chunk of these errors, either it's code in progress or there's a missing import that one can quickly take care of via the quick fix menu (see the screenshot for an example).

Can you provide an option to put these actions at the end instead of the beginning? If that's not easily doable, can you provide an option to get rid of the quick actions entirely? 

Also, it's worth noting that duplicates show if there are multiple actions (also shown in the screenshot). If that's by design (the error message is used in the prompt), it may be nice to provide the user with some context as to which error they're asking about.

![image](https://user-images.githubusercontent.com/19292614/229937570-c4017b9a-01b3-4828-83fc-ef6304418ab8.png)

**Comment by genieai-info** [comment]
Hi there - thanks for the suggestion. We addressed this in the recent release by appending the real error along with the error codde to the quickfix suggestion
