### ISSUE TITLE
Nothing happened after entering api key

### ISSUE THREAD

**Issue by mummumt** [ai-genie/chatgpt-vscode#59]
### Verify it's not a duplicate bug report

- [X] I searched for similar bugs reported on GitHub and nobody has reported a similar issue. <a href="https://github.com/ai-genie/vscode-chatgpt/issues?q=" target="_blank">Search all issuees</a>.
- [X] I read <a href="https://github.com/ai-genie/vscode-chatgpt#troubleshooting" target="_blank">Troubleshooting guide on Readme</a> and there is not a guide on how to solve my problem.

### Describe the Bug

Upon entering the API key and attempting a prompt, no action occurs; the console requests the API key once more.

I tested the same API key using a shell script to directly request a completion, and it functioned as expected.

** Additional context, tried restarting vscode and still won't work

### Please tell us if you have customized any of the extension settings or whether you are using the defaults.

I used the defaults

**Comment by DevDK12** [comment]
I am facing this same issue

**Comment by mummumt** [comment]
**Update: somehow I tried again today and it worked like it should, not sure why but for me its ok now

**Comment by szmcdull** [comment]
I am facing this same issue. This extension is not working from the very first time. I installed it after the old ChatGPT extension told me it was deprecated. Then it never works again.

**Comment by codingToPerfection** [comment]
# after i enter the api key and pressed enter key, nothing happend. Then, whatever I do, the prompt for api key pop up again for input

**Comment by vertigojc** [comment]
I am having the same issue. I enter my key, hit enter, but then each time I make a request the popup to enter my key comes up again. 
I've tried developer: reload window and I've tried fully restarting vscode but it keeps doing the same thing. 

Is there anywhere I can look or ways I can troubleshoot this? It's as if the extension isn't actually saving the key.

**Comment by codingToPerfection** [comment]
# I HAVE SOLVED IT.

I opened the vscode using **administrator** mode. Then entering api key works

**Comment by vertigojc** [comment]
> # I HAVE SOLVED IT.
> I opened the vscode using **administrator** mode. Then entering api key works

Can confirm. That did it for me, too.
