### ISSUE TITLE
How to provide API Key

### ISSUE THREAD

**Issue by ImtiH** [ai-genie/chatgpt-vscode#61]
### Verify it's not a duplicate bug report

- [X] I searched for similar bugs reported on GitHub and nobody has reported a similar issue. <a href="https://github.com/ai-genie/vscode-chatgpt/issues?q=" target="_blank">Search all issuees</a>.
- [X] I read <a href="https://github.com/ai-genie/vscode-chatgpt#troubleshooting" target="_blank">Troubleshooting guide on Readme</a> and there is not a guide on how to solve my problem.

### Describe the Bug

The first time I installed the extension, it asked for an API key 'Genie: Find Bugs', but I didn't have an API Key so I closed the modal. Now after generating an API KEY, I am trying to have that popup open to provide my API key but it shows me the exact same error every time I try to open it and that is "HTTP 401 Unauthorized. Make sure you are properly signed in." and not opening the popup anymore.

what's the best and possible way to provide the API key at this point? 

### Please tell us if you have customized any of the extension settings or whether you are using the defaults.

no

**Comment by eden881** [comment]
The FAQ in `README.md` mentions a command that clears the API key:
https://github.com/ai-genie/chatgpt-vscode/blob/bf4d2b22bd83b8ff28c003e2171c9424c3371766/README.md?plain=1#L203

**Comment by KjellKod** [comment]
OK. The only thing that worked was clicking a barely visible link in the chat window with Genie. 
![Screenshot 2023-06-12 at 12 33 32 PM](https://github.com/ai-genie/chatgpt-vscode/assets/331742/5cd158e7-8fa3-4c7d-a4af-06a533fa2cb9)

This was kind of a horrible user experience and the readme description didn't help at all.

**Comment by zimejin** [comment]
if anyone still has this issue, on VS code you can right click and select command palette.
![image](https://github.com/ai-genie/chatgpt-vscode/assets/20492430/937ed756-88d3-46b6-9485-14fe37789922)

this will open a drop down where you can select the command.
![image](https://github.com/ai-genie/chatgpt-vscode/assets/20492430/d3bb0ab3-8e92-4515-9d95-e82bf3b1e8cc)

After this, hover over a piece of code and select an action for Genie to perform,  VS code will automatically open a dialog where you can enter your API key.
