### ISSUE TITLE
Unsupported data type error using Azure gpt-3.5-turbo

### ISSUE THREAD

**Issue by makeneko** [ai-genie/chatgpt-vscode#66]
### Verify it's not a duplicate bug report

- [X] I searched for similar bugs reported on GitHub and nobody has reported a similar issue. <a href="https://github.com/ai-genie/vscode-chatgpt/issues?q=" target="_blank">Search all issuees</a>.
- [X] I read <a href="https://github.com/ai-genie/vscode-chatgpt#troubleshooting" target="_blank">Troubleshooting guide on Readme</a> and there is not a guide on how to solve my problem.

### Describe the Bug

- create gpt-35-turbo model in azure
- get key to access api
- install chatgpt-vscode 0.0.8
- OS windows 10
- VS Code 1.77.2
- same problem #50 (but I identified the cause )

This bug is because the extension is accessing the wrong API URL.

According to microsoft's api reference, "Completions" is the same URL as "genieai.azure.url," but "Chat completions" is different from "genieai.azure.url."
https://learn.microsoft.com/en-us/azure/cognitive-services/openai/reference

Completions:
~~~
POST https://{your-resource-name}.openai.azure.com/openai/deployments/{deployment-id}/completions?api-version={api-version}
~~~

Chat completions: (chat/ is in between)
~~~
POST https://{your-resource-name}.openai.azure.com/openai/deployments/{deployment-id}/chat/completions?api-version={api-version}
~~~

### Please tell us if you have customized any of the extension settings or whether you are using the defaults.

"genieai.azure.url": "https://{our resource name}.openai.azure.com/openai/deployments/{our deployment name}/completions?api-version=2022-12-01"

### Additional context

I can now respond to chats by rewriting "this. _ apiReverseProxyUrl" in extension.js to:

~~~
"https://{our resource name}.openai.azure.com/openai/deployments/{our deployment name}/chat/completions?api-version=2023-03-15-preview"
~~~

**Comment by makeneko** [comment]
I solved it myself.
In the case of chatgpt 3.5 turbo on azure, I found that I just need to set the URL below.

"https://{our resource name}.openai.azure.com/openai/deployments/{our deployment name}/chat/completions?api-version=2023-03-15-preview"

**Comment by YinAoXiong** [comment]
> I solved it myself. In the case of chatgpt 3.5 turbo on azure, I found that I just need to set the URL below.
> 
> "https://{our resource name}.openai.azure.com/openai/deployments/{our deployment name}/chat/completions?api-version=2023-03-15-preview"

Thank you very much, I have encountered the same problem.
