### ISSUE TITLE
is it possible to add proxy support?

### ISSUE THREAD

**Issue by shencp** [ai-genie/chatgpt-vscode#7]
### Describe the feature

just add the proxy support as this extension:https://github.com/gencay/vscode-chatgpt

**Comment by genieai-info** [comment]
The proxy on the original ChatGPT extension was implemented only for Browser integration, which is no longer supported in this extension.

To utilize proxies in vs code extensions though, you have a couple of options, which are out of this extension's capability but a vs code setting you can use in your vs code. Try adding the following to your user `settings.json`:

```json
"remote.extensionKind": {"genieai.chatgpt-vscode": ["ui"]
```

Also if you are running the proxy locally on http you can bypass the SSL and try adding these (Change URL with your own proxy) in your User `settings.json`:

```json
"http.proxy": "http://127.0.0.1:1234/",
"http.proxyStrictSSL": false,
```

[More on using proxies in extensions](https://code.visualstudio.com/docs/setup/network#_proxy-server-support:~:text=the%20http.proxy%2C%20http.proxyStrictSSL%20and%20http.proxyAuthorization%20variables%20are%20still%20part%20of%20VS%20Code%27s%20settings)

**Comment by shencp** [comment]
Thanks for your response, it works for me right now. 😀

**Comment by qcgm1978** [comment]
`"remote.extensionKind": {"genieai.chatgpt-vscode": ["ui"]` 
What's meaning of this setting? It not work for me. But the following works: 
`"http.proxy": "http://127.0.0.1:1234/",
"http.proxyStrictSSL": false,`

**Comment by IlmariKu** [comment]
If anyone found this issue and is looking to make a reverse-proxy to be used with Genie, here's my implementation of a mock-server for Azure OpenAI. I can input my mock-server URL and have Genie work out of the box with it.

You probably need to add `"http.proxyStrictSSL": false`-rule for it to work.

https://gist.github.com/IlmariKu/ca59013e5a76f3636f02daa75ac93549
