### ISSUE TITLE
Put new chat button same level as the send button

### ISSUE THREAD

**Issue by xhy279** [ai-genie/chatgpt-vscode#8]
### Describe the feature

As what the title suggests, it would be a better user experience(otherwise i need to click more and new chat) and reasonable implementation considering how the api works which needs to append old message so i have to clear conversation quite often.

**Comment by genieai-info** [comment]
Hi - having the `Start a new chat` button right next to `Send message` button could be easily destructive and cause unwanted user experience (i.e. accidentally clicking it while trying to send a message)

Did you see the controls up at the toolbar for `Genie: Start a new chat` command?

![image](https://user-images.githubusercontent.com/128560534/226808507-5bcc863e-5cca-42d7-bcec-b70e8e111e4f.png)

There is also a command for `Genie: Start a new chat`, for which you could assign a keyboard shortcut if you find yourself creating new chats very often, that'd be very useful.

![image](https://user-images.githubusercontent.com/128560534/226808837-cc7bfc15-12da-4602-a3b7-5524fef9d3a8.png)

**Comment by xhy279** [comment]
I see. ty for the tip. Didn't notice that plus button upper there before.

I still think it could be better to put that feature besides the send button, it works like Bing chat. Maybe autofocus can add to this also.  I don't know, your product,  it's just a personal opinion.  

Anyway, gj on this extension.
