### ISSUE TITLE
For the sake of the expert prompt engineer. PLEASE ALLOW US TO CHANGE SYSTEM PROMPT.

### ISSUE THREAD

**Issue by Cytranics** [ai-genie/chatgpt-vscode#83]
### Verify it's not a duplicate bug report

- [X] I searched for similar bugs reported on GitHub and nobody has reported a similar issue. <a href="https://github.com/ai-genie/vscode-chatgpt/issues?q=" target="_blank">Search all issuees</a>.
- [X] I read <a href="https://github.com/ai-genie/vscode-chatgpt#troubleshooting" target="_blank">Troubleshooting guide on Readme</a> and there is not a guide on how to solve my problem.

### Describe the Bug

I have the 32k Azure model. Your extent ion is the only one that works. But the model will never respond with the entire code. Please let us change the prompt, as I can get the 32k model to respond with all the code, but your prompt is blocking that.

### Please tell us if you have customized any of the extension settings or whether you are using the defaults.

Tell me how to customize it and I will, I looked at the JS files, changed them but they wont apply.

I have the 32k Azure model. Your extent ion is the only one that works. But the model will never respond with the entire code. Please let us change the prompt, as I can get the 32k model to respond with all the code, but your prompt is blocking that.

### Additional context

I have the 32k Azure model. Your extent ion is the only one that works. But the model will never respond with the entire code. Please let us change the prompt, as I can get the 32k model to respond with all the code, but your prompt is blocking that.

**Comment by ChuckJonas** [comment]
ya, this drives me crazy.  The default prompt is so bad and generates way to verbose of responses.  This and the lack of open source makes me think i'll move on to something else

**Comment by xmjiao** [comment]
This seems to be one of the biggest complaints about `chatgpt-vscode`. The other fork of `https://github.com/gencay/vscode-chatgpt` (https://github.com/Christopher-Hayes/vscode-chatgpt-reborn) does allow users to change the system prompt. 

You can change the system prompt of this fork is to edit the file `genieai.chatgpt-vscode-<versionnumber>/out/extension.js` manually and then edit the corresponding `genieai.chatgpt-vscode-<versionnumber>/package.json` force reloading the extension. This workaround is clumsy, and the option should be in settings as in `vscode-chatgpt-reborn`.

**Comment by genieai-info** [comment]
Added a new setting `genieai.systemMessage` to customize the initial system message in the new version v0.0.12

https://github.com/ai-genie/chatgpt-vscode/releases/tag/v0.0.12
