### ISSUE TITLE
 Direct Access to OpenAI API without Microsoft Azure

### ISSUE THREAD

**Issue by Konard** [ai-genie/chatgpt-vscode#88]
### Describe the feature

Is there a way to directly use OpenAI API token without need to set up anything in the Microsoft Azure?

If not, please make it possible.

**Comment by viking1304** [comment]
Azure is just a new feature. You can use a plugin without it. Just add your token.

**Comment by jhgorse** [comment]
Add your token... 
https://github.com/ai-genie/chatgpt-vscode#get-started
<img width="584" alt="image" src="https://github.com/ai-genie/chatgpt-vscode/assets/1783474/4fa5792c-39e8-4857-aef0-d4b8c8f7d02c">

Clear the API Key. Attempt to use chat. vs code extension asks for API Key.
