### ISSUE TITLE
Can't delete the API Key

### ISSUE THREAD

**Issue by clearday4** [ai-genie/chatgpt-vscode#9]
### Verify it's not a duplicate bug report

- [X] I searched for similar bugs reported on GitHub and nobody has reported a similar issue. <a href="https://github.com/ai-genie/vscode-chatgpt/issues?q=" target="_blank">Search all issuees</a>.
- [X] I read <a href="https://github.com/ai-genie/vscode-chatgpt#troubleshooting" target="_blank">Troubleshooting guide on Readme</a> and there is not a guide on how to solve my problem.

### Describe the Bug

Select code -> Genie: Add Tests
And the asnwer is : 
"Any messages previously copied" is not a legal HTTP header value.

And there's only the same response to any questions.

I want to send Genie: Reset session or Genie: Clear API Key command
But it returns same response again.

Even though I deleted and re-install genie AI, the API key is not deleted.

### Please tell us if you have customized any of the extension settings or whether you are using the defaults.

model : gpt-4
temperature : 0.5
max tokens : 1024
top_p : 1

**Comment by genieai-info** [comment]
Hi - if you run `Genie: Clear API Key` it will remove your API Key that's stored in VS Code's secrets storage. You could also click `API Key` on the home page (Check left bottom), and in the input prompt remove your API Key and hit Enter. If you hit Escape it will cancel it, but if you remove it and hit Enter it will set the key to empty string.

Could you share a screenshot of your scenario? `"Any messages previously copied" is not a legal HTTP header value.` looks odd to have as a response from ChatGPT. Curious if you have VPN/proxy on your device. Also what is your system details such as OS, version, VS Code version?

**Comment by GuilhermeTiede** [comment]
Where do I put the Genie: Clear API Key command? At the terminal? In the extension settings?

**Comment by genieai-info** [comment]
@GuilhermeTiede 

It's a vscode command that you could open from your command palette. Use `ctrl+shift+p` to open command palette, then type `Genie: Clear API Key`. You can also access your command palette via `Help -> Show all commands`

**Comment by genieai-info** [comment]
> @GuilhermeTiede
> 
> It's a vscode command that you could open from your command palette. Use `ctrl+shift+p` to open command palette, then type `Genie: Clear API Key`. You can also access your command palette via `Help -> Show all commands`

It's not a shell command @clearday4, can you follow these steps? If it still doesn't work, please restart all of your visual studio code instances **after clearing the api key via VS Code Command**, let's see if that helps

**Comment by clearday4** [comment]
> 'any messages previously copied' means that the incorrect API Key I entered. It means that a part of the email content was copied as the API Key value."
> 
> I'm running on Window 10 and the vs code information is : version: 1.76.2 (user setup) commit: ee2b180d582a7f601fa6ecfdad8d9fd269ab1884 date: 2023-03-14T17:55:54.936Z Electron: 19.1.11 Chromium: 102.0.5005.196 Node.js: 16.14.2 V8: 10.2.154.26-electron.0 OS: Windows_NT x64 10.0.18362
> 
> I Try to run command "Genie: Clear API Key" on shell command, but the problem is not cleared.

**Comment by clearday4** [comment]
> > 'any messages previously copied' means that the incorrect API Key I entered. It means that a part of the email content was copied as the API Key value."
> > I'm running on Window 10 and the vs code information is : version: 1.76.2 (user setup) commit: ee2b180d582a7f601fa6ecfdad8d9fd269ab1884 date: 2023-03-14T17:55:54.936Z Electron: 19.1.11 Chromium: 102.0.5005.196 Node.js: 16.14.2 V8: 10.2.154.26-electron.0 OS: Windows_NT x64 10.0.18362
> > I Try to run command "Genie: Clear API Key" on shell command, but the problem is not cleared.

I can clear the API key with shell command.
Thank you for your support!

**Comment by genieai-info** [comment]
is it resolved now?

**Comment by clearday4** [comment]
Thanks.
It is resolved.
But I'm not solving the consecutive 429 errors.

**Comment by genieai-info** [comment]
Check out the 429-error troubleshooting, it's related to your account but could be due to various reasons: https://github.com/ai-genie/chatgpt-vscode#:~:text=If%20you%20get,in%20this%20extension)

OpenAI docs around error codes: https://platform.openai.com/docs/guides/error-codes
