### ISSUE TITLE
Can't use azure  openai,when model_name = gpt-35-turbo

### ISSUE THREAD

**Issue by lingfengchencn** [ai-genie/chatgpt-vscode#94]
### Verify it's not a duplicate bug report

- [X] I searched for similar bugs reported on GitHub and nobody has reported a similar issue. <a href="https://github.com/ai-genie/vscode-chatgpt/issues?q=" target="_blank">Search all issuees</a>.
- [X] I read <a href="https://github.com/ai-genie/vscode-chatgpt#troubleshooting" target="_blank">Troubleshooting guide on Readme</a> and there is not a guide on how to solve my problem.

### Describe the Bug

1、config azure url with date
2、clear old key ，set azure openai key
3、set model  to gpt-3.5-turbo ,not work
4、edit settings.json ,set model to gpt-35-turbo,
5、 work ,but it seems like text-danvici-003

### Please tell us if you have customized any of the extension settings or whether you are using the defaults.

I edit Settings.json, and set it to. gpt-35-turbo. and it seams text-danvici-003.  
on the setting page it's gpt4 

### Additional context

can't us ,and will crash sometimes

**Comment by tvvocold** [comment]
+1

**Comment by WenkangHu** [comment]
same problem

**Comment by romainshen** [comment]
The Azure endpoint URL should be:
i.e.: https://your-endpoint-base.openai.azure.com/openai/deployments/your-azure-model-
name/chat/completions?api-version=2022-12-01

"Chat completions" use the modles: gpt-4, gpt-4-0314, gpt-4-32k, gpt-4-32k-0314, gpt-3.5-turbo, gpt-3.5-turbo-0301,while "Completions" use: text-davinci-003, text-davinci-002, text-curie-001, text-babbage-001, text-ada-001
Ref: [Models - OpenAI API](https://platform.openai.com/docs/models/overview)

**Comment by lingfengchencn** [comment]
> The Azure endpoint URL should be: i.e.: https://your-endpoint-base.openai.azure.com/openai/deployments/your-azure-model- name/chat/completions?api-version=2022-12-01
> 
> "Chat completions" use the modles: gpt-4, gpt-4-0314, gpt-4-32k, gpt-4-32k-0314, gpt-3.5-turbo, gpt-3.5-turbo-0301, while "Completions" use: text-davinci-003, text-davinci-002, text-curie-001, text-babbage-001, text-ada-001
> 
> Ref: [Models - OpenAI API](https://platform.openai.com/docs/models/overview)

Tks， But my model name is gpt-35-turbo not  gpt-3.5-turbo:

<img width="386" alt="image" src="https://github.com/ai-genie/chatgpt-vscode/assets/2757011/ad2416c2-26c0-476d-9983-0da4ae96997c">

**Comment by romainshen** [comment]
The URL was wrong:
https://.../your-azure-model-name/completion/... ->
https://.../your-azure-model-name/chat/completion/...
