### ISSUE TITLE
Please scroll the replies

### ISSUE THREAD

**Issue by OnkelTem** [ai-genie/chatgpt-vscode#95]
### Describe the feature

When chatGPT is answering, there is no autoscrolling, so you have to use your mouse to do it which is highly inconvenient. Please follow the output, updating the scroll position.

Platform: Linux Kubuntu 22.04

**Comment by thxtech** [comment]
I completely agree with this issue.
The original ChatGPT web application automatically scrolls when answering. This extension should work the same way.

**Comment by genieai-info** [comment]
Could you check if your autoscroll setting is turned on? 
![image](https://github.com/ai-genie/chatgpt-vscode/assets/128560534/e1183eb7-f59b-4be0-bd04-950ab9814d7b)
