### ISSUE TITLE
Where is code history?

### ISSUE THREAD

**Issue by OnkelTem** [ai-genie/chatgpt-vscode#96]
### Describe the feature

I was in the code view, entering and polishing my question. Then I clicked the button Optimize, and it just replaced the code it has generated with an unattended example, also replacing my question with "Optimize the following code" text. Now I cannot restore my question, it's not in the chats history , it's just disappeared.

I think either a history should be added to the code view, or those misleading buttons should be removed because they break user input.

**Comment by genieai-info** [comment]
Did you enable the experimental feature to write your conversations in file so you can access them later on?
